[phases.setup]
nixpkgs-archive = "https://github.com/NixOS/nixpkgs/archive/nixos-24.05.tar.gz"

[phases.setup.nix]
nodejs = "20"

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"
